hashgrid_config:
  dtype: full
  n_levels: 5
  n_features_per_level: 4 # 1, 2, 4, 8
  log2_hashmap_size: 8
  base_resolution: 16
  max_resolution: 256
  
resolution: 256

renderer_config:
  dim_in: 20
  dim_out: 3  
  dim_hidden: 256
  num_layers: 4

num_epochs: 1000
lr: 0.0001